name: MCAnalytics
main: com.kmecpp.mcanalytics.Main
author: kmecpp
version: 1.1
description:
   A Minecraft plugin and php script that collects statistics about a server to be displayed from anywhere
commands:
   mcanalytics:
      description: MCAnalytics base command
      aliases: [stats, mcstats, mca]